"""Sync Asset Status Labels

Revision ID: 02633fd2f0b9
Revises: 78dc4edcaa84
Create Date: 2026-05-16 14:01:14.302796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02633fd2f0b9'
down_revision: Union[str, Sequence[str], None] = '78dc4edcaa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
