"""Add payments table

Revision ID: 2984be7b5697
Revises: 93f0a7feddbe
Create Date: 2026-05-16 13:06:44.976083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2984be7b5697'
down_revision: Union[str, Sequence[str], None] = '93f0a7feddbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_snapshots')
    op.add_column('payments', sa.Column('collected_by_id', sa.String(), nullable=True))
    op.alter_column('payments', 'contract_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'vendor_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_payments_vendor_id'), table_name='payments')
    op.drop_constraint(op.f('payments_collected_by_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['collected_by_id'], ['id'])
    op.drop_column('payments', 'collected_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('collected_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_collected_by_fkey'), 'payments', 'users', ['collected_by'], ['id'])
    op.create_index(op.f('ix_payments_vendor_id'), 'payments', ['vendor_id'], unique=False)
    op.alter_column('payments', 'vendor_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'contract_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('payments', 'collected_by_id')
    op.create_table('reconciliation_snapshots',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_expected', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('reconciliation_snapshots_vendor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reconciliation_snapshots_pkey'))
    )
    # ### end Alembic commands ###
