"""Add KYC and vendor_tag

Revision ID: 5a206f1db515
Revises: b237a40789ab
Create Date: 2026-05-16 13:36:32.574504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a206f1db515'
down_revision: Union[str, Sequence[str], None] = 'b237a40789ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('suspension_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'suspension_reason')
    # ### end Alembic commands ###
