"""Add KYC and vendor_tag

Revision ID: 78dc4edcaa84
Revises: 5a206f1db515
Create Date: 2026-05-16 13:56:12.456558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dc4edcaa84'
down_revision: Union[str, Sequence[str], None] = '5a206f1db515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('manager_id', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('internal_id', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_assets_internal_id'), 'assets', ['internal_id'], unique=True)
    op.create_foreign_key(None, 'assets', 'users', ['manager_id'], ['id'])
    op.add_column('financing_contracts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financing_contracts', 'created_at')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_internal_id'), table_name='assets')
    op.drop_column('assets', 'created_at')
    op.drop_column('assets', 'internal_id')
    op.drop_column('assets', 'manager_id')
    # ### end Alembic commands ###
