"""Add KYC and vendor_tag

Revision ID: b237a40789ab
Revises: 2984be7b5697
Create Date: 2026-05-16 13:30:29.520736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b237a40789ab'
down_revision: Union[str, Sequence[str], None] = '2984be7b5697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('vendor_tag', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('cac_number', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('business_address', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('business_type', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_vendors_vendor_tag'), 'vendors', ['vendor_tag'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_vendor_tag'), table_name='vendors')
    op.drop_column('vendors', 'created_at')
    op.drop_column('vendors', 'business_type')
    op.drop_column('vendors', 'contact_phone')
    op.drop_column('vendors', 'business_address')
    op.drop_column('vendors', 'cac_number')
    op.drop_column('vendors', 'vendor_tag')
    # ### end Alembic commands ###
