"""Add Karota number

Revision ID: e97065333e8a
Revises: 02633fd2f0b9
Create Date: 2026-05-16 15:47:15.610924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97065333e8a'
down_revision: Union[str, Sequence[str], None] = '02633fd2f0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('karota_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'assets', ['karota_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='unique')
    op.drop_column('assets', 'karota_number')
    # ### end Alembic commands ###
